### PR TITLE
Updated database oauth example for new FastHTML changes

### PR DESCRIPTION
**Pull request by samueller**

### CODE REVIEW

**Comment by jph00** [comment]
Thank you! Can you please revert the formatting to be the same as it was before, so that your PR has a minimal diff with just the required changes?

**Comment by samueller** [comment]
> Thank you! Can you please revert the formatting to be the same as it was before, so that your PR has a minimal diff with just the required changes?

Yes, my editor automatically formatted it. I'll revert. I notice now that sometimes single quotes were used and sometimes double quotes. Is there a standard we should abide by? Or leave the mix of single and double quotes?

**Comment by jph00** [comment]
There's no standard, other than to avoid changing things unnecessarily, to keep diffs easier to read. Thanks for taking a look!

**Comment by samueller** [comment]
I have reverted the formatting

**Comment by jph00** [comment]
perfect :)

**Pull request merged**
