### PR TITLE
Reset input field after user send a message

### PR DESCRIPTION
**Pull request by inweb3**
Return an additional `ChatInput()` in `send_message` to make sure the user input field is reset after the `Send` button is clicked.

### CODE REVIEW

**Comment by inweb3** [comment]
Added `show:bottom` to `hx_swap` to enable scrolling of assistant messages.

**Comment by johnowhitaker** [comment]
The `show:bottom` makes it impossible to scroll up and read the start of a long message while it's still generating, since it keeps jumping to the bottom of the message. So let's remove that for now and then I'll merge :)

**Comment by inweb3** [comment]
I see. Thanks @johnowhitaker I removed the `show:bottom` commit, please check if it is ok now :)

**Comment by johnowhitaker** [comment]
@inweb3 thank you :)

**Pull request merged**
